### ISSUE TITLE
Max size style doesn't retain aspect ratio

### ISSUE THREAD

**Issue by bemky** [42floors/waitress#15]
Example: https://images.42floors.com/3b9b017132715c9e79f117f591fca757f7ff9da0.jpg?s=1000x700*

compared to

https://images.42floors.com/3b9b017132715c9e79f117f591fca757f7ff9da0.jpg?s=1000x700^

**Comment by bemky** [comment]
but occasionally it works:

https://images.42floors.com/7515e81984a519c8a594cddb0733ff71e42adef7.jpg?s=1000x700*

**Comment by waratuman** [comment]
c7b4623924c78f73451a7f7efa022153769c60ea
